// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcrHqrQ7cghZf5DAknGqupv53FzlTypXs',
    appId: '1:895740225858:android:309b0d39c48056f7c6c0db',
    messagingSenderId: '895740225858',
    projectId: 'afletes-d4e2c',
    storageBucket: 'afletes-d4e2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhgjEkP51zsZUSsL9pjhwin7rhOZJXuOM',
    appId: '1:895740225858:ios:53cca65e43bdcaddc6c0db',
    messagingSenderId: '895740225858',
    projectId: 'afletes-d4e2c',
    storageBucket: 'afletes-d4e2c.appspot.com',
    androidClientId: '895740225858-nr83r84nibk6556kt0r7oh4r1ti0ah4c.apps.googleusercontent.com',
    iosClientId: '895740225858-q1r07em4af6ugbf2sbrjke8pophd689k.apps.googleusercontent.com',
    iosBundleId: 'com.afletes.app',
  );
}
