// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABR2JQopca2hE586rMJTWycoVs4xhsQ00',
    appId: '1:895740225858:web:738bc14e46d1822dc6c0db',
    messagingSenderId: '895740225858',
    projectId: 'afletes-d4e2c',
    authDomain: 'afletes-d4e2c.firebaseapp.com',
    storageBucket: 'afletes-d4e2c.appspot.com',
    measurementId: 'G-TH988V8ZJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcrHqrQ7cghZf5DAknGqupv53FzlTypXs',
    appId: '1:895740225858:android:9292c0f2e8c2c647c6c0db',
    messagingSenderId: '895740225858',
    projectId: 'afletes-d4e2c',
    storageBucket: 'afletes-d4e2c.appspot.com',
  );
}
